### ISSUE TITLE
pelican-ipynb prettification

### ISSUE THREAD

**Issue by vitorsr** [petrnohejl/minimal-xy#4]
Something that was really bugging me was the extra margin whitespace on code cells when rendering Jupyter/IPython Notebooks using the aforementioned plugin.

My temporary fix was commenting out **line 234** on `style.css` on my local clone:
```css
  /* margin: 3rem 0; */
```

Sorry for inverting the order. It's **after** and **before**:
![image](https://user-images.githubusercontent.com/40741601/44633265-2dc9fe80-a95f-11e8-96b7-32339e0dc5dc.png)
I don't know the implications of removing this margin yet.

**Comment by petrnohejl** [comment]
Thanks for your comment. I have to keep this line in CSS, otherwise multiple highlighted blocks don't have enough spacing in between. It wouldn't look good. Example: http://blog.petrnohejl.cz/apache-a-mod_python-pro-webovy-framework-django.
